name = "ghal_examples"
description = "GHAL demo applications - 2048 for STM32F746G-DISCO"
version = "0.1.0"
licenses = "Apache-2.0"
maintainers = ["Olivier Henley <olivier.henley@adacore.com>"]

[build-switches]
"*".runtime_checks = "none"

[[depends-on]]
bitmap                   = "*"
dc_generic               = "*"
fb_generic               = "*"
gesture                  = "*"
touch_generic            = "*"
stm32f746g_disco         = "*"

[[pins]]
stm32f746g_disco = { url = "https://github.com/GNAT-Academic-Program/stm32f746g_disco.git", branch = "main" }
gesture          = { url = "https://github.com/GNAT-Academic-Program/gesture.git", branch = "main" }
bitmap           = { url = "https://github.com/GNAT-Academic-Program/bitmap.git", branch = "main" }
dc_generic       = { url = "https://github.com/GNAT-Academic-Program/dc_generic.git", branch = "main" }
fb_generic       = { url = "https://github.com/GNAT-Academic-Program/fb_generic.git", branch = "main" }
touch_generic    = { url = "https://github.com/GNAT-Academic-Program/touch_generic.git", branch = "main" }
