name = "ghal_examples"
description = "GHAL demo applications - 2048 for STM32F746G-DISCO"
version = "0.1.0"
licenses = "Apache-2.0"
maintainers = ["Olivier Henley <olivier.henley@adacore.com>"]

[build-switches]
"*".runtime_checks = "none"

[[depends-on]]
#machine_types            = "*"
#bitmap                   = "*"
#dc_generic               = "*"
#fb_generic               = "*"
#gesture                  = "*"
#touch_generic            = "*"
stm32f469i_disco         = "*"

[[pins]]
stm32f469i_disco = { path = "../stm32f469i_disco" }
#gesture          = { path = "../gesture" }
#bitmap           = { path = "../bitmap" }
#dc_generic       = { path = "../dc_generic" }
#fb_generic       = { path = "../fb_generic" }
#touch_generic    = { path = "../touch_generic" }
